# Generated by Django 2.2.3 on 2019-07-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauzans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fauzan',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
