# Generated by Django 2.2.4 on 2019-08-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fauzans', '0002_fauzan_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fauzan',
            name='label',
        ),
        migrations.AddField(
            model_name='fauzan',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fauzan',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
