# Generated by Django 2.2.3 on 2019-07-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_de', models.CharField(max_length=50, null=True)),
                ('name_th', models.CharField(max_length=50, null=True)),
                ('name_cn', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_th', models.TextField(blank=True, null=True)),
                ('description_cn', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
